// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensions.MinikubeGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMinikubeGeneratorPkgString = "27dd9dea-6dd2-403e-929d-3ff20d896c5e";
        public const string guidMinikubeGeneratorCmdSetString = "32af8a17-bbbc-4c56-877e-fc6c6575a8cf";
        public static Guid guidMinikubeGeneratorPkg = new Guid(guidMinikubeGeneratorPkgString);
        public static Guid guidMinikubeGeneratorCmdSet = new Guid(guidMinikubeGeneratorCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}
