// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensions.MinikubeDeploy
{
				static class Vsix
				{
								public const string Id = "1ea5fb62-ec48-4634-aeff-0b21038a758e";
								public const string Name = "Minikube Deploy";
								public const string Description = @"The fastest and easiest way to deploy a docker image to the minikube.";
								public const string Language = "en-US";
								public const string Version = "1.1";
								public const string Author = "Luciano Reichert Eger";
								public const string Tags = "minikube, deploy";
				}
}
