// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensions.MinikubeGenerator
{
				static class Vsix
				{
								public const string Id = "99eae45b-eb5d-4f4f-a6a9-9516a0729b56";
								public const string Name = "Minikube Generator";
								public const string Description = @"The fastest and easiest way to deploy a docker image to the minikube.";
								public const string Language = "en-US";
								public const string Version = "1.0";
								public const string Author = "Luciano Reichert Eger";
								public const string Tags = "minikube, deploy";
				}
}
